tap 'homebrew/homebrew-php'

brew 'autoconf'
brew 'curl', args: ['with-openssl']
brew 'ctop'
brew 'exa'
brew 'git'
brew 'gnupg'
brew 'graphviz'
brew 'go'
brew 'highlight'
brew 'kubernetes-helm'
brew 'phive'
brew 'php70'
brew 'php70-xdebug'
brew 'php71'
brew 'php71-xdebug'
brew 'php71-grpc'
brew 'php72'
brew 'pinentry-mac'
brew 'vim', args: ['--override-system-vi']
brew 'watch'
brew 'zsh'
brew 'zsh-syntax-highlighting'